[versions]
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
jetbrains-compose = "1.10.0-rc02"
agp = "8.11.1" # https://kotlinlang.org/docs/multiplatform-compatibility-guide.html#version-compatibility
android-minSdk = "23"
android-targetSdk = "36"

activity-compose = "1.12.1"
appcompat = "1.7.1"
coroutines = "1.10.2"
datastore = "1.2.0"
datetime = "0.7.1"
kermit = "2.0.8"
koin = "4.1.1"
lifecycle = "2.10.0"
material3 = "1.10.0-alpha05"
material3-adaptive = "1.3.0-alpha02"
navigation = "2.9.1"
room = "2.8.4"
serialization = "1.9.0"
splashscreen = "1.2.0"
sqldelight = "2.2.1"
sqlite = "2.6.2"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-koin = { module = "co.touchlab:kermit-koin", version.ref = "kermit" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-android = { module = "io.insert-koin:koin-android" }

lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }

compose-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }

navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-runtime-android = { module = "androidx.room:room-runtime-android", version.ref = "room" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-async-extensions = { module = "app.cash.sqldelight:async-extensions", version.ref = "sqldelight" }

sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

[plugins]
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }

android-application = { id = "com.android.application", version.ref = "agp" }

room = { id = "androidx.room", version.ref = "room" }

sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
